disabled_rules:
  - line_length

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_declaration
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

included:
  - Halo/Halo

excluded:
  - Pods

analyzer_rules:
  - explicit_self
  - unused_import

reporter: "xcode"
